[package]
name = "solar_system_json"
version = "0.1.0"
edition = "2024"

[dependencies]
horizons_solar_system = { path = "../horizons_solar_system" }
hifitime = "4"
serde_json = { version = "1", features = ["preserve_order"] }
clap = { version = "4.5" }