[package]
name = "integration"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"

[dev-dependencies]
num-traits = "0.2.19"
particular = { git = "https://github.com/Canleskis/particular.git", features = [
    "glam",
] }
glam = "0.29"
plotters = "0.3.7"