[package]
name = "integration"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
particular = { git = "https://github.com/Canleskis/particular.git", features = [
    "glam",
] }
bevy_math = { version = "0.15", default-features = false }
plotters = "0.3.7"
